disabled_rules: # rule identifiers to exclude from running
opt_in_rules: # some rules are only opt-in
included: # paths to include during linting. `--path` is ignored if present.
excluded: 
 Pods	# paths to ignore during linting. Takes precedence over `included`.
function_parameter_count: 8
line_length: 120
function_body_length:
  warning: 400 # warning
  error: 600 # error
type_body_length:
  warning: 400 # warning
  error: 600 # error
file_length:
  warning: 300
  error: 700
type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
variable_name:
  min_length: # only min_length
    error: 1 # only error
  excluded: 
  - id # excluded via string array
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
